"""v0.0.1 - Criando Tabelas no Schema API

Revision ID: 2abe63b5f6bd
Revises: 
Create Date: 2024-09-29 16:29:02.692197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abe63b5f6bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cidade', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('imoveis', sa.Integer(), nullable=True),
    sa.Column('trabalhados', sa.Integer(), nullable=True),
    sa.Column('nao_trabalhados', sa.Integer(), nullable=True),
    sa.Column('pend', sa.Float(), nullable=True),
    sa.Column('visitados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='api'
    )
    op.create_index(op.f('ix_api_registros_area'), 'registros', ['area'], unique=False, schema='api')
    op.create_index(op.f('ix_api_registros_id'), 'registros', ['id'], unique=False, schema='api')
    op.create_index(op.f('ix_api_registros_id_cidade'), 'registros', ['id_cidade'], unique=False, schema='api')
    op.create_index(op.f('ix_api_registros_nome'), 'registros', ['nome'], unique=False, schema='api')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_registros_nome'), table_name='registros', schema='api')
    op.drop_index(op.f('ix_api_registros_id_cidade'), table_name='registros', schema='api')
    op.drop_index(op.f('ix_api_registros_id'), table_name='registros', schema='api')
    op.drop_index(op.f('ix_api_registros_area'), table_name='registros', schema='api')
    op.drop_table('registros', schema='api')
    # ### end Alembic commands ###
